# Generated by Django 3.2 on 2021-09-02 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0003_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='buy',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='sell',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
