# Generated by Django 3.2 on 2021-09-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0005_auto_20210902_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='average_purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='total_units',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
