# Generated by Django 3.2 on 2021-09-08 01:53

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0006_auto_20210902_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='previous_close',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='stock',
            name='average_purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True),
        ),
    ]
