# Generated by Django 3.2 on 2021-09-08 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0008_alter_stock_previous_close'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='average_purchase_price',
            new_name='average_buy_price',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='total_units',
            new_name='holding_units',
        ),
    ]
