# Generated by Django 3.2 on 2021-09-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0009_auto_20210908_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='previous_close',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
