# Generated by Django 3.2 on 2021-09-08 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0010_alter_stock_previous_close'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
