# Generated by Django 3.2 on 2021-09-08 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0011_stock_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='name',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='timestamp',
        ),
    ]
