# Generated by Django 3.2 on 2021-09-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0012_auto_20210908_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='stock',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
