# Generated by Django 3.2 on 2021-09-14 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0013_auto_20210908_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='buy',
            new_name='activity',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='previous_close',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='sell',
        ),
    ]
