# Generated by Django 3.2 on 2021-09-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0014_auto_20210914_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='activity',
            field=models.JSONField(default=list, null=True),
        ),
    ]
